languages:
  PHP: true
  JavaScript: true
exclude_paths:
- alice/build/*
- alice/cli/*
- alice/dev/*
- alice/doc/*
- alice/node_nomdules/*
- alice/tmp/*
- "*.md"
- bob/cli/*
- bob/data/*
- bob/docs/*
- Docker/*
- jenkins/*
- library/*
- local/*
- tools/*
- vendor/*
